name: First workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2

      - name: Hello Codelies!
        run: echo "Hello!!!! from ${{ github.workflow }} triggered by the ${{ github.event_name }} done by ${{ github.actor }}"

      - name: ðŸ˜Š More and more
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: |
          echo "Job Context: $JOB_CONTEXT"
          echo "Done!"

      - name: Install dependencies
        working-directory: ./lessons/03-Continuous_Integration/03.1-Executing_tests
        run: composer install --ignore-platform-reqs

      - name: Run the tests
        working-directory: ./lessons/03-Continuous_Integration/03.1-Executing_tests
        run: composer phpunit
